/*******************************************************
*              P6110 - Final Project                   *
********************************************************/

********************************************************
*                    Problem A;                        *
********************************************************;
ODS RTF File='C:\Users\Jovial\Desktop\Final.rtf';
*Part a;
*Scatter plot;
proc sgplot data=ICU;
scatter x=AGE y=STA;
run;
*Frequancy tables;
proc freq data=ICU;
tables CAN*STA / nocol;
run;
proc freq data=ICU;
tables CPR*STA / nocol;
run;
proc freq data=ICU;
tables INF*STA / nocol;
run;
proc freq data=ICU;
tables RACE*STA / nocol;
run;
*Part b,c;
*Fit univariable logistic regressions;
proc logistic data=ICU;
model STA=AGE / cl;
run;
proc format;
value Calfmt 0='No' 1='Yes';
run;
proc logistic data=ICU;
class CAN(ref='No') / param=ref;
model STA=CAN / cl;
format CAN calfmt.;
run;
proc logistic data=ICU;
class CPR(ref='No') / param=ref;
model STA=CPR / cl;
format CPR calfmt.;
run;
proc logistic data=ICU;
class INF(ref='No') / param=ref;
model STA=INF / cl;
format INF calfmt.;
run;
proc format;
value Calfmt 1='White' 2='Black' 3='Other';
run;
proc logistic data=ICU;
class RACE(ref='Other') / param=ref;
model STA=RACE / cl;
format RACE calfmt.;
run;
*Fit multivariable logistic regression;
proc format;
value Calfmt 0='No' 1='Yes';
run;
proc logistic data=ICU descending;
class CPR(ref='No') / param = ref;
class INF(ref='No') / param = ref;
model STA=AGE CPR INF CPR*INF AGE*CPR AGE*INF;
format CPR INF calfmt.;
run;
proc logistic data=ICU descending;
class CPR(ref='No') / param = ref;
model STA=AGE CPR / lackfit;
format CPR calfmt.;
run;
*Part d;
*Create ROC and calculate AUC;
proc format;
value Calfmt 0='No' 1='Yes';
run;
proc logistic data=ICU descending;
class CPR(ref='No') / param = ref;
model STA=AGE CPR / outroc=ROCICU;
format CPR calfmt.;
run;
ODS RTF CLOSE;

********************************************************
*                    Problem B;                        *
********************************************************;
ODS RTF File='C:\Users\Jovial\Desktop\Final.rtf';
*Part a;
*Plot the survial curves;
proc lifetest data=UIS plots=(survival);
time time*censor(0);
strata hercoc / test=(all);
run;
proc lifetest data=UIS plots=(survival);
time time*censor(0);
strata ivhx / test=(all);
run;
proc lifetest data=UIS plots=(survival);
time time*censor(0);
strata race / test=(all);
run;
proc lifetest data=UIS plots=(survival);
time time*censor(0);
strata treat / test=(all);
run;
proc lifetest data=UIS plots=(survival);
time time*censor(0);
strata site / test=(all);
run;
proc lifetest data=UIS plots=(survival);
time time*censor(0);
strata drug / test=(all);
run;
*Cox-proportional hazards;
proc phreg data=UIS;
model time*censor(0)=age/rl;
run;
proc phreg data=UIS;
model time*censor(0)=beck/rl;
run;
proc phreg data=UIS;
model time*censor(0)=ndrugtx/rl;
run;
*Part b;
*Choose the 'best' set of predictors;
proc phreg data=UIS ;
model time*censor(0)=ivhx race drug beck ndrugtx treat;
run;
proc phreg data=UIS ;
class ivhx(ref="1") race(ref="0") drug(ref="0") treat(ref="0");
model time*censor(0)=ivhx race drug beck ndrugtx treat/selection=b;
run;
*Part c;
*Test all two-way interactions;
proc phreg data=UIS;
model time*censor(0)=race treat beck ndrugtx race*treat race*beck race*ndrugtx treat*beck treat*ndrugtx beck*ndrugtx/rl;
run;
*Part d;
*Test the proportionality assumption and functional form;
proc phreg data=UIS;
model time*censor(0) = race treat beck ndrugtx race_t treat_t beck_t ndrugtx_t/rl;
race_t=race*log(time);
treat_t=treat*log(time);
beck_t=beck*log(time);
ndrugtx_t=ndrugtx*log(time);
run;
proc phreg data=UIS;
model time*censor(0)=race treat beck ndrugtx/rl;
assess var=(beck ndrugtx)/resample;
output out=outp xbeta=xb resmart=mart resdev=dev ressch=ressch;
run;
*Part e;
*Perform a residual analysis;
proc gplot data=outp;
title "Deviance residuals plot";
plot dev*xb / cframe=white overlay vref=0 caxis=black;
run;
*Part f;
*Present the hazard ratios and 95% confidence intervals;
proc phreg data=UIS;
model time*censor(0)=race treat beck ndrugtx/rl;
run;
*Part g;
*Make a comparison;
proc phreg data=UIS;
model time*censor(0)=treat/rl;
run;
proc phreg data=UIS;
model time*censor(0)=race treat beck ndrugtx/rl;
run;
ODS RTF CLOSE;
